window_title: Dark and Darker
reference_resolution:
  width: 2560
  height: 1600
market_list:
  left: 420
  top: 678
  width: 1750
  height: 780
refresh_button:
  x: 2080
  y: 436
buy_button:
  x: 1749
  y: 0
trade_dialog:
  submit_button:
    x: 1277
    y: 1088
  complete_button:
    x: 1277
    y: 1182
row_height: 87
ocr:
  lang: chi_sim+eng
  psm: 6
  whitelist: 0123456789,./\goldGOLD金币
